image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and Test'
          script:
            - echo "Building Test..."
      - step:
          name: 'Deployment App'
          deployment: test
          script:
            - echo "Deploying production App"
