image: atlassian/default-image:2

pipelines:
  branches:
    main:
      - step:
          name: Build and Test
          script:
            - echo "Test OK"
      - step:
          name: Build and Push Docker Images
          runs-on:
            - self.hosted
            - linux
          services:
            - docker
          caches:
            - docker
          script:
            - echo "VERSION =" $VERSION
            - echo "Logging in to Docker Hub"
            - echo $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
            - echo "Building Angular App Docker Image"
            - docker build -t pepewee/ucapp-frontend:$VERSION -f Angular/my-front-app/Dockerfile Angular/my-front-app
            - docker tag pepewee/ucapp-frontend:$VERSION pepewee/ucapp-frontend:latest
            - echo "Building Java App Docker Image"
            - docker build -t pepewee/ucapp-backend:$VERSION -f Dockerfile .
            - docker tag pepewee/ucapp-backend:$VERSION pepewee/ucapp-backend:latest
            - echo "Docker images"
            - docker images
            - echo "Pushing Angular App Docker Image"
            - docker push pepewee/ucapp-frontend:$VERSION
            - docker push pepewee/ucapp-frontend:latest
            - echo "Pushing Java App Docker Image"
            - docker push pepewee/ucapp-backend:$VERSION
            - docker push pepewee/ucapp-backend:latest
      - step:
          name: Deploy to Server
          runs-on:
            - self.hosted
            - linux
          script:
            - echo $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
            - docker pull pepewee/ucapp-frontend:latest
            - docker pull pepewee/ucapp-backend:latest
            - docker-compose -f /data/sites/backoffice.ucacue.edu.ec/docker-compose.yml down
            - docker-compose -f /data/sites/backoffice.ucacue.edu.ec/docker-compose.yml up -d

definitions:
  services:
    docker:
      memory: 2048
