version: '3.9'
services:
  angular_app:
    container_name: angular_app
    image: pepewee/ucapp-frontend:1.0.0
    ports:
      - "4200:80"
    depends_on:
      - javaapp

  javaapp:
    container_name: javaapp
    image: pepewee/ucapp-backend:1.0.1
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:13.3
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
