# Etapa de construcción
FROM node:20-alpine AS build

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de definición del paquete y realiza la instalación
COPY package*.json ./

# Utiliza npm ci si package-lock.json está disponible para una instalación más eficiente
RUN npm ci

# Copia el resto del código fuente de la aplicación
COPY . .

# Construye la aplicación para producción
RUN npm run build --prod

# Etapa de producción
FROM nginx:1.27.0-alpine

# Copia los archivos construidos desde la etapa de construcción
COPY --from=build /app/dist/my-front-app /usr/share/nginx/html
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf

#COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exponer el puerto 80 para el servidor Nginx
EXPOSE 80

# Comando para ejecutar Nginx
CMD ["nginx", "-g", "daemon off;"]
