# Usa una imagen base de Node.js para construir y ejecutar la aplicación Angular
FROM node:20-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia package.json y package-lock.json para instalar las dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código de la aplicación
COPY . .

# Exponer el puerto en el que la aplicación Angular se ejecutará
EXPOSE 4200

# Comando para ejecutar la aplicación con hot reload
CMD ["npm", "start"]
